apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portfolio
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml
images:
  - name: ghcr.io/cyokozai/portfolio
    newTag: latest
