apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portfolio
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
- ingress.yaml
images:
- name: ghcr.io/cyokozai/portfolio
  newTag: d34375c4fe149b9d2ea6ae7c7ac4ec4ebbcdf132
